package encryption;


public class encGUI extends javax.swing.JFrame {
    public encGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        substitutionPanel1 = new encryption.substitutionPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        vigenerePanel1 = new encryption.vigenerePanel();
        railFenceCipher1 = new encryption.RailFenceCipher();
        railFencePanel1 = new encryption.railFencePanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transpositionPanel1 = new encryption.transpositionPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(500, 500));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(600, 600));

        jScrollPane1.setViewportView(substitutionPanel1);

        jTabbedPane1.addTab("Substitution", jScrollPane1);

        jScrollPane3.setViewportView(vigenerePanel1);

        jTabbedPane1.addTab("Vigenere", jScrollPane3);

        javax.swing.GroupLayout railFenceCipher1Layout = new javax.swing.GroupLayout(railFenceCipher1);
        railFenceCipher1.setLayout(railFenceCipher1Layout);
        railFenceCipher1Layout.setHorizontalGroup(
            railFenceCipher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(railFencePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        railFenceCipher1Layout.setVerticalGroup(
            railFenceCipher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(railFencePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Rail Fence", railFenceCipher1);

        jScrollPane2.setViewportView(transpositionPanel1);

        jTabbedPane1.addTab("Transposition", jScrollPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 95;
        gridBagConstraints.ipady = 95;
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(encGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(encGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(encGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(encGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new encGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private encryption.RailFenceCipher railFenceCipher1;
    private encryption.railFencePanel railFencePanel1;
    private encryption.substitutionPanel substitutionPanel1;
    private encryption.transpositionPanel transpositionPanel1;
    private encryption.vigenerePanel vigenerePanel1;
    // End of variables declaration//GEN-END:variables
}
